#!/bin/bash
# BSD 2-Clause License
#
# Copyright (c) 2018, Rafael Correia da Silva
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# Modification, are permitted provided that the following conditions are met:
#
# Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# And/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Environment variables
## No. of threads
threads=15

# Variables
readR1=$1
readR2=${2:null}

## Treats single as merged if there is no R2
if [[ ${readR2} = "null" ]]; then
	${merged} = ${readR1}
fi

# Program to Run
## OPT 1: VirusDetect
do_run="VirusDetect"

### VirusDetect parameters
vd_evalue="1e-10"
vd_identity="0.90"
vd_targetdb="vrl_plant"

# Strip R1, R2 and fastq basename"
fqbase=`basename ${readR1} .fastq | sed 's/_R1.*//'`
fqmerged="merged/${fqbase}.merged.fastq"

## Main VirusDetect pipe
if [[ ${do_run} = "VirusDetect" ]]; then
	

	# Checks if MERGED exists,
	# if not, runs PEAR to do it
	if [[ ! -f ${fqmerged} ]]; then

	# Run pear
	echo "There is not a merged file!"
	echo

	fi
	
	echo "Starting VirusDetect analysis"
	echo
	echo "The time is:"
	date

	VirusDetect \
		--reference ${vd_targetdb} \
		--thread_num ${threads} \
		--exp_value ${vd_evalue} \
		--percent_identity ${vd_identity} \
		${fqmerged}

	echo "Analysis finished for VirusDetect"

fi



